[project]
name = "intromcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=3.2.4",
    "geopandas>=1.1.3",
    "googlemaps>=4.10.0",
    "ipykernel>=7.2.0",
    "langchain>=1.2.17",
    "langchain-groq>=1.1.2",
    "langchain-mcp-adapters>=0.2.2",
    "pyarrow>=24.0.0",
    "pydotenv>=0.0.7",
    "redis>=8.1.0",
    "ruff>=0.15.12",
]
